"""add call table

Revision ID: 52216f7fb73e
Revises: 782f3cc442d8
Create Date: 2026-02-13 08:16:39.068360

"""

# revision identifiers, used by Alembic.
revision = '52216f7fb73e'
down_revision = '782f3cc442d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('call_sid', sa.String(length=100), nullable=True))
    op.add_column('calls', sa.Column('record_sid', sa.String(length=100), nullable=True))
    op.add_column('calls', sa.Column('recording_url', sa.String(length=400), nullable=True))
    op.add_column('calls', sa.Column('conversation_text', sa.TEXT(), nullable=True))
    op.add_column('calls', sa.Column('patient_phone', sa.String(length=20), nullable=True))
    op.add_column('calls', sa.Column('carrier_phone', sa.String(length=20), nullable=True))
    op.add_column('calls', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('calls', sa.Column('prosody_results', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'calls', ['record_sid'])
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_column('calls', 'patient_id')
    op.drop_column('calls', 'twilio_sid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('twilio_sid', sa.VARCHAR(), nullable=True))
    op.add_column('calls', sa.Column('patient_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'calls', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'calls', type_='unique')
    op.drop_column('calls', 'prosody_results')
    op.drop_column('calls', 'is_processed')
    op.drop_column('calls', 'carrier_phone')
    op.drop_column('calls', 'patient_phone')
    op.drop_column('calls', 'conversation_text')
    op.drop_column('calls', 'recording_url')
    op.drop_column('calls', 'record_sid')
    op.drop_column('calls', 'call_sid')
    # ### end Alembic commands ###
