"""Add created_by_id to QuestionSet

Revision ID: 078b2d4d54b8
Revises: 0d74757b1fe1
Create Date: 2026-04-22 18:35:45.110070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078b2d4d54b8'
down_revision = '0d74757b1fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_patients_therapist_id_users', 'users', ['therapist_id'], ['id'])

    with op.batch_alter_table('question_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_question_sets_created_by_id_users', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_sets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_sets_created_by_id_users', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patients_therapist_id_users', type_='foreignkey')

    # ### end Alembic commands ###
