"""Add QuestionSet table

Revision ID: 0d74757b1fe1
Revises: bb8081f98354
Create Date: 2026-04-22 16:05:37.260449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d74757b1fe1'
down_revision = 'bb8081f98354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=50), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch', 'lang', name='uq_question_set_batch_lang')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_patients_therapist_id_users', 'users', ['therapist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patients_therapist_id_users', type_='foreignkey')

    op.drop_table('question_sets')
    # ### end Alembic commands ###
