"""Add User model and update Patient for multi-therapist support

Revision ID: 9351f5b9cb60
Revises: 7c479d056ef6
Create Date: 2026-03-23 15:16:10.853215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9351f5b9cb60'
down_revision = '7c479d056ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('batch', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )

    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('batch', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('therapist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_patients_therapist_id', 'users', ['therapist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patients_therapist_id', type_='foreignkey')
        batch_op.drop_column('deleted')
        batch_op.drop_column('therapist_id')
        batch_op.drop_column('batch')
        batch_op.drop_column('nickname')

    op.drop_table('users')
    # ### end Alembic commands ###
