"""Add ProsodyParameter model for storing parameter explanations

Revision ID: bb8081f98354
Revises: 9351f5b9cb60
Create Date: 2026-03-24 10:16:00.621181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8081f98354'
down_revision = '9351f5b9cb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prosody_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_key', sa.String(length=100), nullable=False),
    sa.Column('parameter_name', sa.String(length=200), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_key')
    )
    # Foreign key already exists from previous migration
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prosody_parameters')
    # ### end Alembic commands ###
